name: Deploy Create React App

on:
  push:
    branches:
      - main  # Укажите ветку, на которую будет происходить пуш

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Сборка приложения

      - name: Install sshpass
        run: sudo apt-get install -y sshpass  # Установка sshpass для использования пароля

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy files to server via SSH
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}       # Имя пользователя для SSH
          SERVER_IP: ${{ secrets.SERVER_IP }}           # IP-адрес сервера
          SERVER_PATH: ${{ secrets.SERVER_PATH }}       # Путь на сервере, куда будут копироваться файлы
          SERVER_PASSWORD: ${{ secrets.PASSWORD }} # Пароль для SSH
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "ls -la /"
          sshpass -p "$SERVER_PASSWORD" rsync -avz --delete ./build/ $SERVER_USER@$SERVER_IP:$SERVER_PATH